In [ ]:
import pandas as pd
df = pd.read_csv('vgsales.csv')

# Data Cleaning
df['Year'] = df['Year'].fillna(df['Year'].median())
df['Publisher']= df['Publisher'].fillna('Unknown')

In [9]:
df.isna().sum()

Rank              0
Name              0
Platform          0
Year              0
Genre             0
Publisher         0
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
Sales_Category    0
Year_Category     0
Publisher_Size    0
dtype: int64

In [10]:
# Pengelompokan Penjualan Berdasarkan penjualan Global
df_sales_kategory =  pd.cut (
    df['Global_Sales'],
    bins=[0,30,50, df['Global_Sales'].max()],
    labels=['Low', 'Medium', 'High'],
    include_lowest=True
)

df['Sales_Category'] = df_sales_kategory

# Kateghori Tahun Rilis 
df_era_category = pd.cut(
    df['Year'],
    bins= [1965, 2005, 2018, 2026],
    labels=['Old', 'Modern', 'Recent']
)

df['Year_Category'] = df_era_category

# Main Region 
df['Main_Region'] = df[
    ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']
].idxmax(axis=1)

df['Main_Region'] = df['Main_Region'].str.replace('_Sales', '')
# Kategory Publisher
publisher_sales = df.groupby('Publisher')['Global_Sales'].transform('sum')

df['Publisher_Size'] = pd.cut(
    publisher_sales,
    bins=[0, 50, 200, publisher_sales.max()],
    labels=['Small', 'Medium', 'Big']
)

In [3]:
df[df['Year_Category'].isnull()][['Year', 'Year_Category']]

Empty DataFrame
Columns: [Year, Year_Category]
Index: []

In [ ]:
df['genre'].count.values

Publisher
Electronic Arts                 1351
Activision                       975
Namco Bandai Games               932
Ubisoft                          921
Konami Digital Entertainment     832
                                ...
Media Entertainment                1
New World Computing                1
Genterprise                        1
Rain Games                         1
UIG Entertainment                  1
Name: count, Length: 578, dtype: int64

In [ ]:
df.to_csv('games', index = False)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Sales_Category,Year_Category,Publisher_Size,Main_Region
0,1,Wii Sports,Wii,2006.0,Sports,Nintendo,41.49,29.02,3.77,8.46,82.74,High,Modern,Big,NA
1,2,Super Mario Bros.,NES,1985.0,Platform,Nintendo,29.08,3.58,6.81,0.77,40.24,Medium,Old,Big,NA
2,3,Mario Kart Wii,Wii,2008.0,Racing,Nintendo,15.85,12.88,3.79,3.31,35.82,Medium,Modern,Big,NA
3,4,Wii Sports Resort,Wii,2009.0,Sports,Nintendo,15.75,11.01,3.28,2.96,33.00,Medium,Modern,Big,NA
4,5,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,Nintendo,11.27,8.89,10.22,1.00,31.37,Medium,Old,Big,NA